In [ ]:
import os
import pathlib
from typing import List
from datasets import load_dataset, concatenate_datasets, ClassLabel
import evaluate
import torch
from transformers import Trainer, TrainingArguments, DataCollatorWithPadding
from hf_wrapper import GPTForSequenceClassification
from model import GPT, GPTConfig
from tokenizer import load_tokenizer, eod_token
from sklearn.metrics import precision_score, recall_score, f1_score

# --- Config ---
train_lang = 'ru'      
eval_lang = 'ru'    

BASE_DIR = pathlib.Path("/fs/scratch/PAS2836/ipa_gpt")
TOKENIZER_DIR = pathlib.Path("/fs/ess/PAS2836/ipa_gpt/tokenizers")

CHECKPOINTS = {
    "ipa": BASE_DIR / "checkpoints/russian_polish_ipa_12_5_50k/ckpt.pt",
    "normal": BASE_DIR / "checkpoints/russian_polish_normal_12_5_50k/ckpt.pt",
}

TOKENIZERS = {
    "ipa": (
        TOKENIZER_DIR / "bpe-rus-pol-ipa-number-preservation-vocab.json",
        TOKENIZER_DIR / "bpe-rus-pol-ipa-number-preservation-merges.txt",
    ),
    "normal": (
        TOKENIZER_DIR / "bpe-rus-pol-normal-number-preservation-vocab.json",
        TOKENIZER_DIR / "bpe-rus-pol-normal-number-preservation-merges.txt",
    ),
}

LANG_TO_DATASET = {
    "ru": "iggy12345/sentirueval2016-ipa",
    "pl": "iggy12345/allegro-reviews-ipa"
}

args = {
    'epochs': 8,
    'context_size': 1024,
    'learning_rate': 2e-5,
    'batch_size': 16,
    'hf_cache_dir': pathlib.Path('cache'),
    'device': 'cuda',
}

def load_pretrained_model(path: pathlib.Path, device: str = 'cuda') -> GPT:
    checkpoint = torch.load(path, map_location=device)
    gptconf = GPTConfig(**checkpoint['model_args'])
    model = GPT(gptconf)
    state_dict = checkpoint['model']
    unwanted_prefix = '_orig_mod.'
    for k in list(state_dict.keys()):
        if k.startswith(unwanted_prefix):
            state_dict[k[len(unwanted_prefix):]] = state_dict.pop(k)
    filtered = {k: v for k, v in state_dict.items()
                if k in model.state_dict() and v.shape == model.state_dict()[k].shape}
    model.load_state_dict({**model.state_dict(), **filtered})
    return model.to(device)

def flatten_multi_features(examples, features: List[str]) -> List[str]:
    sep = f'\n\n{eod_token}\n\n'
    return [sep.join([x or '' for x in items]) for items in zip(*[examples[f] for f in features])]

def get_fields(example, model_type):
    if model_type == "ipa":
        if 'premise-phoneme' in example:
            return ['premise-phoneme', 'hypothesis-phoneme']
        elif 'sentence_A-phoneme' in example:
            return ['sentence_A-phoneme', 'sentence_B-phoneme']
    if 'premise' in example:
        return ['premise', 'hypothesis']
    return ['sentence_A', 'sentence_B']

def load_and_preprocess(dataset_name, split, tokenizer, model_type):
    ds = load_dataset(dataset_name, split=split, cache_dir=str(args['hf_cache_dir']))
    if 'label' in ds.features and not isinstance(ds.features['label'], ClassLabel):
        ds = ds.cast_column("label", ClassLabel(names=['entailment', 'neutral', 'contradiction']))
    sample = ds[0]
    fields = get_fields(sample, model_type)

    def preprocess(examples):
        features = flatten_multi_features(examples, fields)
        return tokenizer(features, truncation=True, max_length=args['context_size'])

    return ds.map(preprocess, batched=True)

metric = evaluate.load("xnli", "en")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = torch.from_numpy(logits).argmax(dim=-1)
    labels = torch.from_numpy(labels)

    correct = (preds == labels).sum().item()
    total = len(labels)
    accuracy = correct / total

    return {
        "accuracy": accuracy,
        "precision": precision_score(labels, preds, average="weighted", zero_division=0),
        "recall": recall_score(labels, preds, average="weighted", zero_division=0),
        "f1": f1_score(labels, preds, average="weighted", zero_division=0)
    }

# === Run both IPA and NORMAL models ===
for model_type in ['ipa', 'normal']:
    print(f"\n🔧 Running setup for {model_type.upper()} model")
    vocab_path, merges_path = TOKENIZERS[model_type]
    tokenizer = load_tokenizer(vocab_path, merges_path)
    base_model = load_pretrained_model(CHECKPOINTS[model_type], args['device'])
    base_model.config.pad_token_id = tokenizer.pad_token_id
    base_model.config.padding_side = tokenizer.padding_side
    model = GPTForSequenceClassification(base_model, num_classes=3).to(args['device'])

    if train_lang == 'both':
        train_ru = load_and_preprocess(LANG_TO_DATASET['ru'], 'train', tokenizer, model_type)
        train_pl = load_and_preprocess(LANG_TO_DATASET['pl'], 'train', tokenizer, model_type)
        train_dataset = concatenate_datasets([train_ru, train_pl]).shuffle(seed=42)
    else:
        train_dataset = load_and_preprocess(LANG_TO_DATASET[train_lang], 'train', tokenizer, model_type)

    if eval_lang == 'both':
        eval_ru = load_and_preprocess(LANG_TO_DATASET['ru'], 'validation', tokenizer, model_type)
        eval_pl = load_and_preprocess(LANG_TO_DATASET['pl'], 'train', tokenizer, model_type)       #change to pl[20%] when required
        eval_dataset = concatenate_datasets([eval_ru, eval_pl])
    elif eval_lang == 'ru':
        eval_dataset = load_and_preprocess(LANG_TO_DATASET['ru'], 'validation', tokenizer, model_type)
    else:
        eval_dataset = load_and_preprocess(LANG_TO_DATASET['pl'], 'train', tokenizer, model_type)   #change to pl[20%] when required

    output_dir = pathlib.Path(f"./training_outputs_rupl/{train_lang}2{eval_lang}_{model_type}")
    output_dir.mkdir(parents=True, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        eval_strategy="steps",
        eval_steps=1000,
        save_strategy="steps",
        save_steps=1000,
        save_total_limit=1,
        metric_for_best_model="precision",
        load_best_model_at_end=True,
        learning_rate=args['learning_rate'],
        per_device_train_batch_size=args['batch_size'],
        per_device_eval_batch_size=args['batch_size'],
        num_train_epochs=args['epochs'],
        weight_decay=0.01,
        logging_steps=1000,
        logging_dir='./logs',
        fp16=True,
        disable_tqdm=False,
        warmup_ratio=0.3,
        seed=42,
        save_safetensors=False
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
        compute_metrics=compute_metrics,
    )

    print(f"Training {model_type.upper()} model on {train_lang.upper()} → Evaluating on {eval_lang.upper()}")
    trainer.train()

    print(f"Final evaluation on {eval_lang.upper()} for model {model_type.upper()}")
    results = trainer.evaluate()
    print(results)

🔧 Running setup for IPA model
number of parameters: 123.35M

Map: 100%|██████████| 392702/392702 [00:55<00:00, 7073.97 examples/s]
Map: 100%|██████████| 7200/7200 [00:00<00:00, 9848.50 examples/s]
Map: 100%|██████████| 2490/2490 [00:00<00:00, 8480.30 examples/s]
/tmp/slurmtmp.1601692/ipykernel_3883042/4257188652.py:161: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training IPA model on BOTH → Evaluating on BOTH

In [3]:
from collections import Counter
from datasets import load_dataset, ClassLabel

# Load dataset
ds = load_dataset("iggy12345/cdsc-e-ipa", split="train")

# Manually cast label column to ClassLabel
label_names = ['entailment', 'neutral', 'contradiction']
ds = ds.cast_column("label", ClassLabel(names=label_names))

# Count label distribution
label_counts = Counter(ds["label"])

print("📊 Class Distribution in Polish Training Set:")
for idx, count in sorted(label_counts.items()):
    print(f"{label_names[idx]:>15}: {count} samples")

Casting the dataset: 100%|██████████| 7200/7200 [00:00<00:00, 336737.87 examples/s]

📊 Class Distribution in Polish Training Set:
     entailment: 559 samples
        neutral: 5344 samples
  contradiction: 1297 samples

In [5]:
import os
import pathlib
from typing import List
from datasets import load_dataset, concatenate_datasets, ClassLabel
import evaluate
import torch
from transformers import Trainer, TrainingArguments, DataCollatorWithPadding
from hf_wrapper import GPTForSequenceClassification
from model import GPT, GPTConfig
from tokenizer import load_tokenizer, eod_token
from sklearn.metrics import precision_score, recall_score, f1_score

# --- Config ---
BASE_DIR = pathlib.Path("/fs/scratch/PAS2836/ipa_gpt")
TOKENIZER_DIR = pathlib.Path("/fs/ess/PAS2836/ipa_gpt/tokenizers")

CHECKPOINTS = {
    "ipa": BASE_DIR / "checkpoints/russian_polish_ipa_12_5_50k/ckpt.pt",
    "normal": BASE_DIR / "checkpoints/russian_polish_normal_12_5_50k/ckpt.pt",
}

TOKENIZERS = {
    "ipa": (
        TOKENIZER_DIR / "bpe-rus-pol-ipa-number-preservation-vocab.json",
        TOKENIZER_DIR / "bpe-rus-pol-ipa-number-preservation-merges.txt",
    ),
    "normal": (
        TOKENIZER_DIR / "bpe-rus-pol-normal-number-preservation-vocab.json",
        TOKENIZER_DIR / "bpe-rus-pol-normal-number-preservation-merges.txt",
    ),
}

LANG_TO_DATASET = {
    "ru": "iggy12345/xnli-ru-ipa",
    "pl": "iggy12345/cdsc-e-ipa"
}

args = {
    'epochs': 3,
    'context_size': 1024,
    'learning_rate': 2e-5,
    'batch_size': 16,
    'hf_cache_dir': pathlib.Path('cache'),
    'device': 'cuda',
}

def load_pretrained_model(path: pathlib.Path, device: str = 'cuda') -> GPT:
    checkpoint = torch.load(path, map_location=device)
    gptconf = GPTConfig(**checkpoint['model_args'])
    model = GPT(gptconf)
    state_dict = checkpoint['model']
    unwanted_prefix = '_orig_mod.'
    for k in list(state_dict.keys()):
        if k.startswith(unwanted_prefix):
            state_dict[k[len(unwanted_prefix):]] = state_dict.pop(k)
    filtered = {k: v for k, v in state_dict.items()
                if k in model.state_dict() and v.shape == model.state_dict()[k].shape}
    model.load_state_dict({**model.state_dict(), **filtered})
    return model.to(device)

def flatten_multi_features(examples, features: List[str]) -> List[str]:
    sep = f'\n\n{eod_token}\n\n'
    return [sep.join([x or '' for x in items]) for items in zip(*[examples[f] for f in features])]

def get_fields(model_type, dataset_name):
    if model_type == "ipa":
        if "cdsc" in dataset_name:
            return ["sentence_A-phoneme", "sentence_B-phoneme"]
        else:
            return ["premise-phoneme", "hypothesis-phoneme"]
    else:
        if "cdsc" in dataset_name:
            return ["sentence_A", "sentence_B"]
        else:
            return ["premise", "hypothesis"]

def load_and_preprocess(dataset_name, split, tokenizer, model_type):
    ds = load_dataset(dataset_name, split=split, cache_dir=str(args['hf_cache_dir']))
    if 'label' in ds.features and not isinstance(ds.features['label'], ClassLabel):
        ds = ds.cast_column("label", ClassLabel(names=['entailment', 'neutral', 'contradiction']))
    fields = get_fields(model_type, dataset_name)
    def preprocess(examples):
        features = flatten_multi_features(examples, fields)
        return tokenizer(features, truncation=True, max_length=args['context_size'])
    return ds.map(preprocess, batched=True)

metric = evaluate.load("xnli", "en")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = torch.from_numpy(logits).argmax(dim=-1)
    labels = torch.tensor(labels)
    return {
        "accuracy": (preds == labels).sum().item() / len(labels),
        "precision": precision_score(labels, preds, average="weighted", zero_division=0),
        "recall": recall_score(labels, preds, average="weighted", zero_division=0),
        "f1": f1_score(labels, preds, average="weighted", zero_division=0),
    }

# === Train on RU+PL, Evaluate on RU+PL ===
for model_type in ['ipa', 'normal']:
    print(f"Starting run for {model_type.upper()} on BOTH (RU+PL)")

    # Load tokenizer and model
    vocab_path, merges_path = TOKENIZERS[model_type]
    tokenizer = load_tokenizer(vocab_path, merges_path)
    base_model = load_pretrained_model(CHECKPOINTS[model_type], args['device'])
    base_model.config.pad_token_id = tokenizer.pad_token_id
    base_model.config.padding_side = tokenizer.padding_side
    model = GPTForSequenceClassification(base_model, num_classes=3).to(args['device'])

    # Load + preprocess datasets
    train_ru = load_and_preprocess(LANG_TO_DATASET['ru'], 'train', tokenizer, model_type)
    train_pl = load_and_preprocess(LANG_TO_DATASET['pl'], 'train', tokenizer, model_type)
    train_dataset = concatenate_datasets([train_ru, train_pl])

    eval_ru = load_and_preprocess(LANG_TO_DATASET['ru'], 'validation', tokenizer, model_type)
    eval_pl = load_and_preprocess(LANG_TO_DATASET['pl'], 'train[:20%]', tokenizer, model_type)
    eval_dataset = concatenate_datasets([eval_ru, eval_pl])

    # Setup training args
    output_dir = pathlib.Path(f"./training_outputs_rupl/both2both_{model_type}")
    output_dir.mkdir(parents=True, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        eval_strategy="steps",
        eval_steps=1000,
        save_strategy="steps",
        save_steps=1000,
        save_total_limit=1,
        metric_for_best_model="f1",
        load_best_model_at_end=True,
        learning_rate=args['learning_rate'],
        per_device_train_batch_size=args['batch_size'],
        per_device_eval_batch_size=args['batch_size'],
        num_train_epochs=args['epochs'],
        weight_decay=0.01,
        logging_steps=1000,
        logging_dir='./logs',
        fp16=True,
        disable_tqdm=False,
        warmup_ratio=0.3,
        save_safetensors=False
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
        compute_metrics=compute_metrics,
    )

    print(f"Training {model_type.upper()} model on RU+PL → Evaluating on RU+PL")
    trainer.train()

    print(f"Final evaluation on RU+PL for {model_type.upper()}")
    results = trainer.evaluate()
    print(results)

Starting run for IPA on BOTH (RU+PL)
number of parameters: 123.35M

/tmp/slurmtmp.1596623/ipykernel_2800811/3955839931.py:147: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training IPA model on RU+PL → Evaluating on RU+PL

Final evaluation on RU+PL for IPA

{'eval_loss': 0.5748856663703918, 'eval_accuracy': 0.7498727735368956, 'eval_precision': 0.7504381233174913, 'eval_recall': 0.7498727735368956, 'eval_f1': 0.7468538428384804, 'eval_runtime': 4.3059, 'eval_samples_per_second': 912.707, 'eval_steps_per_second': 57.131, 'epoch': 3.0}
Starting run for NORMAL on BOTH (RU+PL)
number of parameters: 123.35M

/tmp/slurmtmp.1596623/ipykernel_2800811/3955839931.py:147: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Training NORMAL model on RU+PL → Evaluating on RU+PL

Final evaluation on RU+PL for NORMAL

{'eval_loss': 0.5490922927856445, 'eval_accuracy': 0.82264631043257, 'eval_precision': 0.8231742864948823, 'eval_recall': 0.82264631043257, 'eval_f1': 0.8210897804278658, 'eval_runtime': 1.8642, 'eval_samples_per_second': 2108.143, 'eval_steps_per_second': 131.96, 'epoch': 3.0}

In [7]:
import os
import pathlib
from typing import List
from datasets import load_dataset, concatenate_datasets, ClassLabel
import evaluate
import torch
from transformers import Trainer, TrainingArguments, DataCollatorWithPadding
from hf_wrapper import GPTForSequenceClassification
from model import GPT, GPTConfig
from tokenizer import load_tokenizer, eod_token
from sklearn.metrics import precision_score, recall_score, f1_score

# --- Config ---
BASE_DIR = pathlib.Path("/fs/scratch/PAS2836/ipa_gpt")
TOKENIZER_DIR = pathlib.Path("/fs/ess/PAS2836/ipa_gpt/tokenizers")

CHECKPOINTS = {
    "ipa": BASE_DIR / "checkpoints/russian_polish_ipa_12_5_50k/ckpt.pt",
    "normal": BASE_DIR / "checkpoints/russian_polish_normal_12_5_50k/ckpt.pt",
}

TOKENIZERS = {
    "ipa": (
        TOKENIZER_DIR / "bpe-rus-pol-ipa-number-preservation-vocab.json",
        TOKENIZER_DIR / "bpe-rus-pol-ipa-number-preservation-merges.txt",
    ),
    "normal": (
        TOKENIZER_DIR / "bpe-rus-pol-normal-number-preservation-vocab.json",
        TOKENIZER_DIR / "bpe-rus-pol-normal-number-preservation-merges.txt",
    ),
}

LANG_TO_DATASET = {
    "ru": "iggy12345/xnli-ru-ipa",
    "pl": "iggy12345/cdsc-e-ipa"
}

args = {
    'epochs': 3,
    'context_size': 1024,
    'learning_rate': 2e-5,
    'batch_size': 32,
    'hf_cache_dir': pathlib.Path('cache'),
    'device': 'cuda',
}

def load_pretrained_model(path: pathlib.Path, device: str = 'cuda') -> GPT:
    checkpoint = torch.load(path, map_location=device)
    gptconf = GPTConfig(**checkpoint['model_args'])
    model = GPT(gptconf)
    state_dict = checkpoint['model']
    unwanted_prefix = '_orig_mod.'
    for k in list(state_dict.keys()):
        if k.startswith(unwanted_prefix):
            state_dict[k[len(unwanted_prefix):]] = state_dict.pop(k)
    filtered = {k: v for k, v in state_dict.items()
                if k in model.state_dict() and v.shape == model.state_dict()[k].shape}
    model.load_state_dict({**model.state_dict(), **filtered})
    return model.to(device)

def flatten_multi_features(examples, features: List[str]) -> List[str]:
    sep = f'\n\n{eod_token}\n\n'
    return [sep.join([x or '' for x in items]) for items in zip(*[examples[f] for f in features])]

def get_fields(model_type, dataset_name):
    if model_type == "ipa":
        if "cdsc" in dataset_name:
            return ["sentence_A-phoneme", "sentence_B-phoneme"]
        else:
            return ["premise-phoneme", "hypothesis-phoneme"]
    else:
        if "cdsc" in dataset_name:
            return ["sentence_A", "sentence_B"]
        else:
            return ["premise", "hypothesis"]

def load_and_preprocess(dataset_name, split, tokenizer, model_type):
    ds = load_dataset(dataset_name, split=split, cache_dir=str(args['hf_cache_dir']))
    if 'label' in ds.features and not isinstance(ds.features['label'], ClassLabel):
        ds = ds.cast_column("label", ClassLabel(names=['entailment', 'neutral', 'contradiction']))
    fields = get_fields(model_type, dataset_name)
    def preprocess(examples):
        features = flatten_multi_features(examples, fields)
        return tokenizer(features, truncation=True, max_length=args['context_size'])
    return ds.map(preprocess, batched=True)

metric = evaluate.load("xnli", "en")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = torch.from_numpy(logits).argmax(dim=-1)
    labels = torch.tensor(labels)
    return {
        "accuracy": (preds == labels).sum().item() / len(labels),
        "precision": precision_score(labels, preds, average="weighted", zero_division=0),
        "recall": recall_score(labels, preds, average="weighted", zero_division=0),
        "f1": f1_score(labels, preds, average="weighted", zero_division=0),
    }

# === Train on RU+PL, Evaluate on RU+PL ===
# === Train on RU+PL, Evaluate on RU and PL separately ===
for model_type in ['ipa', 'normal']:
    print(f"🚀 Starting run for {model_type.upper()} on BOTH (RU+PL)")

    # Load tokenizer and model
    vocab_path, merges_path = TOKENIZERS[model_type]
    tokenizer = load_tokenizer(vocab_path, merges_path)
    base_model = load_pretrained_model(CHECKPOINTS[model_type], args['device'])
    base_model.config.pad_token_id = tokenizer.pad_token_id
    base_model.config.padding_side = tokenizer.padding_side
    model = GPTForSequenceClassification(base_model, num_classes=3).to(args['device'])

    # Load + preprocess datasets
    train_ru = load_and_preprocess(LANG_TO_DATASET['ru'], 'train', tokenizer, model_type)
    train_pl = load_and_preprocess(LANG_TO_DATASET['pl'], 'train', tokenizer, model_type)
    train_dataset = concatenate_datasets([train_ru, train_pl])

    output_dir = pathlib.Path(f"./training_outputs_rupl/both2split_{model_type}")
    output_dir.mkdir(parents=True, exist_ok=True)

    training_args = TrainingArguments(
        output_dir=str(output_dir),
        eval_strategy="steps",
        eval_steps=4000,
        save_strategy="steps",
        save_steps=4000,
        save_total_limit=1,
        metric_for_best_model="f1",
        load_best_model_at_end=True,
        learning_rate=args['learning_rate'],
        per_device_train_batch_size=args['batch_size'],
        per_device_eval_batch_size=args['batch_size'],
        num_train_epochs=args['epochs'],
        weight_decay=0.01,
        logging_steps=4000,
        logging_dir='./logs',
        fp16=True,
        disable_tqdm=False,
        warmup_ratio=0.3,
        save_safetensors=False
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=train_ru,  # dummy for init
        tokenizer=tokenizer,
        data_collator=DataCollatorWithPadding(tokenizer=tokenizer),
        compute_metrics=compute_metrics,
    )

    print(f"🧠 Training {model_type.upper()} model on RU+PL")
    trainer.train()

    # Evaluate separately on RU
    print(f"\n🔍 Final Evaluation on RU for {model_type.upper()}")
    eval_ru = load_and_preprocess(LANG_TO_DATASET['ru'], 'validation', tokenizer, model_type)
    ru_results = trainer.evaluate(eval_dataset=eval_ru)
    print(ru_results)

    # Evaluate separately on PL
    print(f"\n🔍 Final Evaluation on PL for {model_type.upper()}")
    eval_pl = load_and_preprocess(LANG_TO_DATASET['pl'], 'train[:20%]', tokenizer, model_type)
    pl_results = trainer.evaluate(eval_dataset=eval_pl)
    print(pl_results)

🚀 Starting run for IPA on BOTH (RU+PL)
number of parameters: 123.35M

Map: 100%|██████████| 392702/392702 [01:07<00:00, 5836.90 examples/s]
Map: 100%|██████████| 7200/7200 [00:00<00:00, 10625.57 examples/s]
/tmp/slurmtmp.1596623/ipykernel_2800811/2188855857.py:143: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🧠 Training IPA model on RU+PL

🔍 Final Evaluation on RU for IPA

Map: 100%|██████████| 2490/2490 [00:00<00:00, 6679.87 examples/s]

{'eval_loss': 0.8334956169128418, 'eval_accuracy': 0.6261044176706827, 'eval_precision': 0.6555941966716061, 'eval_recall': 0.6261044176706827, 'eval_f1': 0.625599445915144, 'eval_runtime': 2.912, 'eval_samples_per_second': 855.092, 'eval_steps_per_second': 26.786, 'epoch': 3.0}

🔍 Final Evaluation on PL for IPA

Map: 100%|██████████| 1440/1440 [00:00<00:00, 10213.06 examples/s]

{'eval_loss': 0.10929588973522186, 'eval_accuracy': 0.9583333333333334, 'eval_precision': 0.9579805652580422, 'eval_recall': 0.9583333333333334, 'eval_f1': 0.9576295355752682, 'eval_runtime': 1.3746, 'eval_samples_per_second': 1047.548, 'eval_steps_per_second': 32.736, 'epoch': 3.0}
🚀 Starting run for NORMAL on BOTH (RU+PL)
number of parameters: 123.35M

Map: 100%|██████████| 392702/392702 [00:19<00:00, 20148.61 examples/s]
Map: 100%|██████████| 7200/7200 [00:00<00:00, 23907.47 examples/s]
/tmp/slurmtmp.1596623/ipykernel_2800811/2188855857.py:143: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

🧠 Training NORMAL model on RU+PL

🔍 Final Evaluation on RU for NORMAL

Map: 100%|██████████| 2490/2490 [00:00<00:00, 18895.35 examples/s]

{'eval_loss': 0.8224889039993286, 'eval_accuracy': 0.7188755020080321, 'eval_precision': 0.7277596219355167, 'eval_recall': 0.7188755020080321, 'eval_f1': 0.7190978872626289, 'eval_runtime': 0.785, 'eval_samples_per_second': 3171.829, 'eval_steps_per_second': 99.358, 'epoch': 3.0}

🔍 Final Evaluation on PL for NORMAL

Map: 100%|██████████| 1440/1440 [00:00<00:00, 21512.78 examples/s]

{'eval_loss': 0.026300277560949326, 'eval_accuracy': 0.99375, 'eval_precision': 0.9938017955801104, 'eval_recall': 0.99375, 'eval_f1': 0.9937152414049613, 'eval_runtime': 0.4519, 'eval_samples_per_second': 3186.561, 'eval_steps_per_second': 99.58, 'epoch': 3.0}